name: Deploy to Smithery

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/*/smithery.yaml'
      - 'packages/*/src/**'
      - 'packages/*/Dockerfile'
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to deploy'
        required: true
        type: choice
        options:
          - yelp-fusionai-mcp
          - server-stochasticthinking
          - server-clear-thought

jobs:
  deploy-to-smithery:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Smithery CLI
      run: npm install -g @smithery/cli
    
    - name: Login to Smithery
      run: smithery login
      env:
        SMITHERY_TOKEN: ${{ secrets.SMITHERY_TOKEN }}
    
    - name: Deploy specified package (manual trigger)
      if: github.event_name == 'workflow_dispatch'
      run: |
        cd packages/${{ github.event.inputs.package }}
        smithery deploy
    
    - name: Deploy changed packages (auto trigger)
      if: github.event_name == 'push'
      run: |
        # Get list of changed packages
        CHANGED_PACKAGES=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -o "packages/[^/]*" | sort | uniq)
        
        for package in $CHANGED_PACKAGES; do
          # Check if smithery.yaml exists
          if [ -f "$package/smithery.yaml" ]; then
            echo "Deploying $package to Smithery"
            cd $package
            smithery deploy
            cd ../..
          fi
        done